### ISSUE TITLE
Configure with sqlite doesn't work

### ISSUE THREAD

**Issue by moc32** [embedthis/appweb#574]
Configure with sqlite doesn't work: error message "Cannot find definition for component: sqlite.me"

command sample: ./configure --with sqlite --with http --with pcre
All component exists except sqlite, in appweb 4.3 sqlite package was included. 

If anyone know how I can add support for sqlite, please let me know

thank you

**Comment by embedthis** [comment]
Do 
    pak install sqlite
    ./configure --with sqlite

**Comment by moc32** [comment]
I have already sqlite installed on the host system. What do you mean by pak install sqlite?

**Comment by moc32** [comment]
I have installed the 'pak' tool then install sqlite package as stated. I have configured appweb with sqlite and everything works so far. But when I try to build using 'me' I have an error message stating that sqlite3.h is missing <<< Command failure: src/esp/espLib.c:8832:25: fatal error: sqlite3.h
Do I need to modify something in the source code to be able to build appweb with sqlite?

**Comment by embedthis** [comment]
Do you have sqlite3.h under src/sqlite and under paks/sqlite?

**Comment by moc32** [comment]
I am trying to migrate to appweb-6.2.1 to take advantage of TLS support. As I reported with my very first post, there was no problem building appweb-4.3 with sqlite.

The problem appeared with appweb-6.2.1 
I used "pak install sqlite" which installed indeed sqlite and I can confirm that I have sqlite3.h under "paks/sqlite/dist/" and "src/sqlite/"

I also want to specify the location where I want to install appweb but the "prefix" I gave during the configure step is ignored. In appweb-4.3 I didn't have such an issue.

Thank you for your help

**Comment by moc32** [comment]
I modified src/esp/espLib.c and included sqlite3.h as following " #include    "../sqlite/sqlite3.h"
I can now build with sqlite
I tried to deploy the application for the target platform but unfortunately only folders are created, no file is copied
Deploy command: sudo me --sets core,lib --deploy /opt/cross-compile/appweb/target-tls
The deploy directory is the same I used for the --prefix

**Comment by embedthis** [comment]
There should already be:

```
#if ME_COM_SQLITE
 #include    "sqlite3.h"
```

in the espLib.c. When MakeMe is run, the generated me.h should define ME_COM_SQLITE to 1. So that should include sqlite.

Do the deploy without the --sets. You are missing key sets. See manifest.me under installs for the list of sets and deployment rules.

**Comment by moc32** [comment]
Indeed ME_COM_SQLITE is already defined that's why I get the error "could not find sqlite3.h", you can retry it yourself
"
Download appweb-6.2.1
pak install sqlite
./configure --with sqlite
me
"
you should get the same error

Also I tried to deploy without --sets but it is still the same: folder are created but no binary was copied

**Comment by embedthis** [comment]
Something basic is wrong.

Here are the steps and it works every time here on all our systems.

1. cd appweb-directory

2. pak install sqlite

3. You should now have paks/sqlite and src/sqlite/sqlite3.h. This command should confirm:
```
find . -name sqlite3.h
./paks/sqlite/dist/sqlite3.h
./src/sqlite/sqlite3.h
```

4. ./configure --with sqlite
```
./configure --with sqlite
 [Configure] macosx-x64-debug
     [Found] compiler: C/C++ Compiler: /usr/bin/clang
     [Found] esp: Embedthis ESP, the amazingly fast C-Language web framework
     [Found] http: Embedthis Http Library
     [Found] lib: Library Archive Tool: /usr/bin/ar
     [Found] mbedtls: MbedTLS Support: src/mpr-mbedtls
     [Found] mdb: Embedthis MDB Database
     [Found] mpr: Embedthis Multithreaded Portable Runtime
     [Found] osdep: O/S Dependent Layer
     [Found] pcre: PCRE Library
     [Found] sqlite: SQLite Library
     [Found] ssl: Secure Socket Layer Interface (MbedTLS Support)
     [Found] watchdog: Embedthis Watchdog: build/macosx-x64-debug/bin/appman
    [Create] build/macosx-x64-debug/platform.me
    [Create] build/macosx-x64-debug/inc/me.h
    [Create] start.me
      [Info] Type "me" to build.
```

5. Run Makeme:

```
me
/Users/mob/dev/appweb> me
      [Copy] build/macosx-x64-debug/inc/osdep.h
      [Copy] build/macosx-x64-debug/inc/embedtls.h
      [Copy] build/macosx-x64-debug/inc/mbedtls.h
   [Compile] build/macosx-x64-debug/obj/mbedtls.o
   [Archive] build/macosx-x64-debug/bin/libmbedtls.a
      [Copy] build/macosx-x64-debug/inc/mpr.h
   [Compile] build/macosx-x64-debug/obj/mpr-mbedtls.o
   [Archive] build/macosx-x64-debug/bin/libmpr-mbedtls.a
   [Compile] build/macosx-x64-debug/obj/mprLib.o
      [Link] build/macosx-x64-debug/bin/libmpr.dylib
      [Copy] build/macosx-x64-debug/inc/pcre.h
   [Compile] build/macosx-x64-debug/obj/pcre.o
      [Link] build/macosx-x64-debug/bin/libpcre.dylib
      [Copy] build/macosx-x64-debug/inc/http.h
   [Compile] build/macosx-x64-debug/obj/httpLib.o
      [Link] build/macosx-x64-debug/bin/libhttp.dylib
      [Copy] build/macosx-x64-debug/inc/mpr-version.h
   [Compile] build/macosx-x64-debug/obj/mpr-version.o
   [Archive] build/macosx-x64-debug/bin/libmpr-version.a
      [Copy] build/macosx-x64-debug/inc/esp.h
   [Compile] build/macosx-x64-debug/obj/espLib.o
      [Copy] build/macosx-x64-debug/inc/sqlite3.h
   [Compile] build/macosx-x64-debug/obj/sqlite3.o
...
```

6. Note that sqlite3.h was copied to build/macosx-x64-debug/inc which is the standard include directory passed to ALL make commands

7. You can confirm this via:

```
me -r -s
...
      [Copy] build/macosx-x64-debug/inc/sqlite3.h
      [Copy] cp /Users/mob/dev/appweb/src/sqlite/sqlite3.h /Users/mob/dev/appweb/build/macosx-x64-debug/inc/sqlite3.h
   [Compile] build/macosx-x64-debug/obj/sqlite3.o
       [Run] /usr/bin/clang -c -o build/macosx-x64-debug/obj/sqlite3.o -arch x86_64  -Wno-unused-result -g -w -DEMBEDTHIS=1 -DME_DEBUG=1 "-Ibuild/macosx-x64-debug/inc"  src/sqlite/sqlite3.c
      [Link] build/macosx-x64-debug/bin/libsql.dylib
       [Run] /usr/bin/clang -dynamiclib -o build/macosx-x64-debug/bin/libsql.dylib -arch x86_64 -g -Wl,-rpath,@executable_path/ -Wl,-rpath,@loader_path/ -Lbuild/macosx-x64-debug/bin -install_name @rpath/libsql.dylib -compatibility_version 6.2 -current_version 6.2 "build/macosx-x64-debug/obj/sqlite3.o" -ldl -lpthread -lm

```

**Comment by moc32** [comment]
Hello everyone
This gets weird, I can't have the same behaviour you get. Here are the outputs of the deferent commands in my side:
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
mdiakhite@DEV-ELECDAN:~/backup/works$
mdiakhite@DEV-ELECDAN:~/backup/works$ ls
appweb-6.2.1-src.tgz  old-pkg
mdiakhite@DEV-ELECDAN:~/backup/works$ tar -xf appweb-6.2.1-src.tgz
mdiakhite@DEV-ELECDAN:~/backup/works$ cd appweb-6.2.1/
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls src
appweb.h  convenience.c  http          mbedtls  mpr-mbedtls  osdep  server
certs     customize.h    libappweb.me  modules  mpr-openssl  pcre   utils
config.c  esp            makerom       mpr      mpr-version  rom.c  watchdog
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls pak
ls: cannot access pak: No such file or directory
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls paks/
certs  http     mbedtls  mpr-mbedtls  mpr-version  pcre  watchdog
esp    makerom  mpr      mpr-openssl  osdep        ssl
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ pak install sqlite
   [Install] sqlite 1.0.4
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls src/sqlite/
sqlite3.c  sqlite3.h  sqlite.c  sqlite.me
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls pa
package.json  paks/
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls paks/
certs/       makerom/     mpr-mbedtls/ osdep/       ssl/
esp/         mbedtls/     mpr-openssl/ pcre/        watchdog/
http/        mpr/         mpr-version/ sqlite/
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls paks/
certs/       makerom/     mpr-mbedtls/ osdep/       ssl/
esp/         mbedtls/     mpr-openssl/ pcre/        watchdog/
http/        mpr/         mpr-version/ sqlite/
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ls paks/sqlite/dist/
sqlite3.c  sqlite3.h  sqlite.c  sqlite.me
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ ./configure --with sqlite
 [Configure] linux-x86-debug
     [Found] compiler: C/C++ Compiler: /usr/bin/gcc
     [Found] esp: Embedthis ESP, the amazingly fast C-Language web framework
     [Found] http: Embedthis Http Library
     [Found] lib: Library Archive Tool: /usr/bin/ar
     [Found] mbedtls: MbedTLS Support: src/mpr-mbedtls
     [Found] mdb: Embedthis MDB Database
     [Found] mpr: Embedthis Multithreaded Portable Runtime
     [Found] osdep: Embedthis O/S Dependent Layer
     [Found] pcre: PCRE Library
     [Found] sqlite: SQLite Library
     [Found] ssl: Secure Socket Layer Interface (MbedTLS Support)
     [Found] watchdog: Embedthis Watchdog: build/linux-x86-debug/bin/appman
    [Create] build/linux-x86-debug/platform.me
    [Create] build/linux-x86-debug/inc/me.h
    [Create] start.me
      [Info] Type "me" to build.
mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ me
      [Copy] build/linux-x86-debug/inc/osdep.h
      [Copy] build/linux-x86-debug/inc/embedtls.h
      [Copy] build/linux-x86-debug/inc/mbedtls.h
   [Compile] build/linux-x86-debug/obj/mbedtls.o
   [Archive] build/linux-x86-debug/bin/libmbedtls.a
      [Copy] build/linux-x86-debug/inc/mpr.h
   [Compile] build/linux-x86-debug/obj/mpr-mbedtls.o
   [Archive] build/linux-x86-debug/bin/libmpr-mbedtls.a
   [Compile] build/linux-x86-debug/obj/mprLib.o
      [Link] build/linux-x86-debug/bin/libmpr.so
      [Copy] build/linux-x86-debug/inc/pcre.h
   [Compile] build/linux-x86-debug/obj/pcre.o
      [Link] build/linux-x86-debug/bin/libpcre.so
      [Copy] build/linux-x86-debug/inc/http.h
   [Compile] build/linux-x86-debug/obj/httpLib.o
      [Link] build/linux-x86-debug/bin/libhttp.so
      [Copy] build/linux-x86-debug/inc/mpr-version.h
   [Compile] build/linux-x86-debug/obj/mpr-version.o
   [Archive] build/linux-x86-debug/bin/libmpr-version.a
      [Copy] build/linux-x86-debug/inc/esp.h
   [Compile] build/linux-x86-debug/obj/espLib.o
me: ERROR: Building target /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/obj/espLib.o

Command failure: src/esp/espLib.c:8832:25: fatal error: sqlite3.h: No such file or directory
compilation terminated.


mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

2. Extract of build/linux-x86-debug/inc/me.h
337 #ifndef ME_COM_SQLITE
338     #define ME_COM_SQLITE 1
339 #endif

3. Extract of src/esp/espLib.c
8826 /********************************** Includes **********************************/
8827
8828 #include    "http.h"
8829
8830
8831 #if ME_COM_SQLITE
8832  #include    "sqlite3.h"
8833
8834 #ifndef ME_MAX_SQLITE_MEM
8835     #define ME_MAX_SQLITE_MEM      (2*1024*1024)   /**< Maximum buffering for Sq
8836 #endif
8837 #ifndef ME_MAX_SQLITE_DURATION
8838     #define ME_MAX_SQLITE_DURATION 30000           /**< Database busy timeout */
8839 #endif
8840
8841 /************************************* Local **********************************/

4. If I provide the complete directory of sqlite3.h (src/sqlite/sqlite3.h), I get a successful build. 

5. The deploy command (me --deploy deploydirectory) still copy only folders not files.

I am sorry to bother you but this really get confusing as everything used to work fine with appweb-4.3.3

**Comment by embedthis** [comment]
Please do a 

```
me -s
```
to show the actual commands.

Also, please use markdown in your posts. Use three back-ticks around code blocks. Much easier to read.

**Comment by moc32** [comment]
`mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$ me -s
      [Copy] build/linux-x86-debug/inc/osdep.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/osdep/osdep.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/osdep.h
      [Copy] build/linux-x86-debug/inc/embedtls.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/mbedtls/embedtls.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/embedtls.h
      [Copy] build/linux-x86-debug/inc/mbedtls.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/mbedtls/mbedtls.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/mbedtls.h
   [Compile] build/linux-x86-debug/obj/mbedtls.o
       [Run] /usr/bin/gcc -c -o build/linux-x86-debug/obj/mbedtls.o  -Wno-unused-result -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC -DMBEDTLS_USER_CONFIG_FILE="embedtls.h" "-Ibuild/linux-x86-debug/inc"  src/mbedtls/mbedtls.c
   [Archive] build/linux-x86-debug/bin/libmbedtls.a
       [Run] /usr/bin/ar -cr build/linux-x86-debug/bin/libmbedtls.a "build/linux-x86-debug/obj/mbedtls.o"
      [Copy] build/linux-x86-debug/inc/mpr.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/mpr/mpr.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/mpr.h
   [Compile] build/linux-x86-debug/obj/mpr-mbedtls.o
       [Run] /usr/bin/gcc -c -o build/linux-x86-debug/obj/mpr-mbedtls.o  -Wno-unused-result -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC -D_FILE_OFFSET_BITS=64 -DMBEDTLS_USER_CONFIG_FILE="embedtls.h" "-Ibuild/linux-x86-debug/inc"  src/mpr-mbedtls/mpr-mbedtls.c
   [Archive] build/linux-x86-debug/bin/libmpr-mbedtls.a
       [Run] /usr/bin/ar -cr build/linux-x86-debug/bin/libmpr-mbedtls.a "build/linux-x86-debug/obj/mpr-mbedtls.o"
   [Compile] build/linux-x86-debug/obj/mprLib.o
       [Run] /usr/bin/gcc -c -o build/linux-x86-debug/obj/mprLib.o  -Wno-unused-result -Wall -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC -D_FILE_OFFSET_BITS=64 -DMBEDTLS_USER_CONFIG_FILE="embedtls.h" "-Ibuild/linux-x86-debug/inc"  src/mpr/mprLib.c
      [Link] build/linux-x86-debug/bin/libmpr.so
       [Run] /usr/bin/gcc -shared -o build/linux-x86-debug/bin/libmpr.so -g -rdynamic -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/ -Lbuild/linux-x86-debug/bin "build/linux-x86-debug/obj/mprLib.o" -lmpr-mbedtls -lmbedtls -lrt -ldl -lpthread -lm
      [Copy] build/linux-x86-debug/inc/pcre.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/pcre/pcre.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/pcre.h
   [Compile] build/linux-x86-debug/obj/pcre.o
       [Run] /usr/bin/gcc -c -o build/linux-x86-debug/obj/pcre.o  -Wno-unused-result -Wall -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC "-Ibuild/linux-x86-debug/inc"  src/pcre/pcre.c
      [Link] build/linux-x86-debug/bin/libpcre.so
       [Run] /usr/bin/gcc -shared -o build/linux-x86-debug/bin/libpcre.so -g -rdynamic -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/ -Lbuild/linux-x86-debug/bin "build/linux-x86-debug/obj/pcre.o" -lrt -ldl -lpthread -lm
      [Copy] build/linux-x86-debug/inc/http.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/http/http.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/http.h
   [Compile] build/linux-x86-debug/obj/httpLib.o
       [Run] /usr/bin/gcc -c -o build/linux-x86-debug/obj/httpLib.o  -Wno-unused-result -Wall -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC -D_FILE_OFFSET_BITS=64 -DMBEDTLS_USER_CONFIG_FILE="embedtls.h" "-Ibuild/linux-x86-debug/inc"  src/http/httpLib.c
      [Link] build/linux-x86-debug/bin/libhttp.so
       [Run] /usr/bin/gcc -shared -o build/linux-x86-debug/bin/libhttp.so -g -rdynamic -Wl,--enable-new-dtags -Wl,-rpath,$ORIGIN/ -Lbuild/linux-x86-debug/bin "build/linux-x86-debug/obj/httpLib.o" -lpcre -lmpr -lrt -ldl -lpthread -lm -lmpr-mbedtls -lmbedtls
      [Copy] build/linux-x86-debug/inc/mpr-version.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/mpr-version/mpr-version.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/mpr-version.h
   [Compile] build/linux-x86-debug/obj/mpr-version.o
       [Run] /usr/bin/gcc -c -o build/linux-x86-debug/obj/mpr-version.o  -Wno-unused-result -Wall -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC "-Ibuild/linux-x86-debug/inc"  src/mpr-version/mpr-version.c
   [Archive] build/linux-x86-debug/bin/libmpr-version.a
       [Run] /usr/bin/ar -cr build/linux-x86-debug/bin/libmpr-version.a "build/linux-x86-debug/obj/mpr-version.o"
      [Copy] build/linux-x86-debug/inc/esp.h
      [Copy] cp /home/mdiakhite/backup/works/appweb-6.2.1/src/esp/esp.h /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/inc/esp.h
   [Compile] build/linux-x86-debug/obj/espLib.o
       [Run] /usr/bin/gcc -c -o build/linux-x86-debug/obj/espLib.o  -Wno-unused-result -Wall -g -fPIC -DME_DEBUG=1 -D_REENTRANT -DPIC -D_FILE_OFFSET_BITS=64 -DMBEDTLS_USER_CONFIG_FILE="embedtls.h" "-Ibuild/linux-x86-debug/inc"  src/esp/espLib.c
me: ERROR: Building target /home/mdiakhite/backup/works/appweb-6.2.1/build/linux-x86-debug/obj/espLib.o

Command failure: src/esp/espLib.c:8832:25: fatal error: sqlite3.h: No such file or directory
compilation terminated.


mdiakhite@DEV-ELECDAN:~/backup/works/appweb-6.2.1$`

**Comment by embedthis** [comment]
For some reason on your system, sqlite is not being built before esp.

As a workaround. do:

```
me sqlite compile
```

Can you also please do

```
me dump
```

and email the *.dmp file to dev@embedthis.com

**Comment by embedthis** [comment]
Here is a potential workaround:

In the src/esp/esp.me file, add one line:

```
Me.load({
    blend: [ 'http', '?sqlite' ],

    targets: {
        esp: {
            configurable: true,
            depends:      [ 'libesp', 'mdb' ],
            uses:         [ 'sqlite' ],
        },

        mdb: {
            configurable: true,
            description: 'Embedthis MDB Database’,
>>>> ADD THE LINE BELOW
            uses:    [ 'sqlite' ],
        },
```
That will force sqlite to be built first.

**Comment by moc32** [comment]
```
diakhite@diakhite-VirtualBox:~/Documents/Install/appweb-6.2.1$ pak install sqlite
   [Install] sqlite 1.0.4
```
```
diakhite@diakhite-VirtualBox:~/Documents/Install/appweb-6.2.1$ ./configure --with sqlite
 [Configure] linux-x86-debug
     [Found] compiler: C/C++ Compiler: /usr/bin/gcc
     [Found] esp: Embedthis ESP, the amazingly fast C-Language web framework
     [Found] http: Embedthis Http Library
     [Found] lib: Library Archive Tool: /usr/bin/ar
     [Found] mbedtls: MbedTLS Support: src/mpr-mbedtls
     [Found] mdb: Embedthis MDB Database
     [Found] mpr: Embedthis Multithreaded Portable Runtime
     [Found] osdep: Embedthis O/S Dependent Layer
     [Found] pcre: PCRE Library
     [Found] sqlite: SQLite Library
     [Found] ssl: Secure Socket Layer Interface (MbedTLS Support)
     [Found] watchdog: Embedthis Watchdog: build/linux-x86-debug/bin/appman
    [Create] build/linux-x86-debug/platform.me
    [Create] build/linux-x86-debug/inc/me.h
    [Create] start.me
      [Info] Type "me" to build.
```
```
diakhite@diakhite-VirtualBox:~/Documents/Install/appweb-6.2.1$ me
      [Copy] build/linux-x86-debug/inc/osdep.h
      [Copy] build/linux-x86-debug/inc/mbedtls.h
   [Compile] build/linux-x86-debug/obj/mbedtls.o
   [Archive] build/linux-x86-debug/bin/libmbedtls.a
      [Copy] build/linux-x86-debug/inc/mpr.h
   [Compile] build/linux-x86-debug/obj/mpr-mbedtls.o
   [Archive] build/linux-x86-debug/bin/libmpr-mbedtls.a
   [Compile] build/linux-x86-debug/obj/mprLib.o
      [Link] build/linux-x86-debug/bin/libmpr.so
   [Compile] build/linux-x86-debug/obj/pcre.o
      [Link] build/linux-x86-debug/bin/libpcre.so
      [Copy] build/linux-x86-debug/inc/http.h
   [Compile] build/linux-x86-debug/obj/httpLib.o
      [Link] build/linux-x86-debug/bin/libhttp.so
      [Copy] build/linux-x86-debug/inc/mpr-version.h
   [Compile] build/linux-x86-debug/obj/mpr-version.o
   [Archive] build/linux-x86-debug/bin/libmpr-version.a
      [Copy] build/linux-x86-debug/inc/sqlite3.h
   [Compile] build/linux-x86-debug/obj/sqlite3.o
      [Link] build/linux-x86-debug/bin/libsql.so
      [Copy] build/linux-x86-debug/inc/esp.h
   [Compile] build/linux-x86-debug/obj/espLib.o
      [Link] build/linux-x86-debug/bin/libesp.so
      [Copy] build/linux-x86-debug/inc/appweb.h
   [Compile] build/linux-x86-debug/obj/config.o
   [Compile] build/linux-x86-debug/obj/convenience.o
   [Compile] build/linux-x86-debug/obj/rom.o
   [Compile] build/linux-x86-debug/obj/cgiHandler.o
   [Compile] build/linux-x86-debug/obj/espHandler.o
      [Link] build/linux-x86-debug/bin/libappweb.so
   [Compile] build/linux-x86-debug/obj/appweb.o
      [Link] build/linux-x86-debug/bin/appweb
   [Compile] build/linux-x86-debug/obj/authpass.o
      [Link] build/linux-x86-debug/bin/authpass
   [Compile] build/linux-x86-debug/obj/esp.o
      [Link] build/linux-x86-debug/bin/appweb-esp
      [Copy] extras => build/linux-x86-debug/bin
   [Compile] build/linux-x86-debug/obj/http.o
      [Link] build/linux-x86-debug/bin/http
      [Copy] install-certs => build/linux-x86-debug/bin
   [Compile] build/linux-x86-debug/obj/makerom.o
      [Link] build/linux-x86-debug/bin/makerom
   [Compile] build/linux-x86-debug/obj/sqlite.o
      [Link] build/linux-x86-debug/bin/sqlite
   [Compile] build/linux-x86-debug/obj/watchdog.o
      [Link] build/linux-x86-debug/bin/appman
  [Complete] all
```
```
diakhite@diakhite-VirtualBox:~/Documents/Install/appweb-6.2.1$ sudo me install
[sudo] password for diakhite:
      [Stop] Embedthis Appweb
   [Install] Embedthis Appweb
      [Copy] File sets: core,libs,web,service,esp,utils,test,dev,doc
       [Run] appman install enable start
      [Info] Embedthis Appweb installed at /usr/local/lib/appweb/6.2.1
      [Info] Configuration directory /etc/appweb
      [Info] Documents directory /var/www/appweb
      [Info] Executables directory /usr/local/lib/appweb/6.2.1/bin
      [Info] Use "man appweb" for usage
      [Info] Use appman [start|stop|restart] to control
      [Info] Browse to http://localhost
  [Complete] install
```
```
diakhite@diakhite-VirtualBox:~/Documents/Install/appweb-6.2.1$ app
apparmor_parser  appesp           appman           apport-cli       apport-unpack    appweb
apparmor_status  appletviewer     apport-bug       apport-collect   appres           appweb-esp
diakhite@diakhite-VirtualBox:~/Documents/Install/appweb-6.2.1$ appweb -h
appweb: error while loading shared libraries: libsql.so: cannot open shared object file: No such file or directory
```
`diakhite@diakhite-VirtualBox:~/Documents/Install/appweb-6.2.1$`

**Comment by embedthis** [comment]
Will be fixed in 6.2.2
